server:
  port: 8080
  error:
    include-exception: false
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-message: always
  servlet:
    context-path: /natwest


spring:
  datasource:
    url: jdbc:h2:mem:natwest
    driver-class-name: org.h2.driver
    username:
      natwest
    password: natwest
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


